import { Button, Group, Paper, Text, TextInput } from '@mantine/core';
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
	const [cityInput, setCityInput] = useState('');

	async function getWeatherData() {
		console.log('Button clicked');
		// https://api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}
	}
	return (
		<div className={styles.container}>
			<Head>
				<title>Weather App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main
				style={{
					position: 'static',
					height: '100vh',
					backgroundImage: "url('https://unsplash.com/photos/HAl6CKxM3xU')",
					backgroundSize: 'cover',
				}}
			>
				<div
					style={{
						position: 'absolute',
						left: '50%',
						top: '50%',
						transform: 'translate(-50%, -50%)',
					}}
				>
					<Paper withBorder p='lg' style={{ maxWidth: '500px' }}>
						<Group position='apart'>
							<Text size='xl' weight={500}>
								Get the Weather!
							</Text>
						</Group>
						<Group position='apart' mb='sm'>
							<Text size='lg'>Enter the city and get the weather below</Text>
						</Group>
						<Group position='apart' mb='md'>
							<TextInput
								label='City Name'
								placeholder='ex: New Delhi'
								onChange={(e) => setCityInput(e.target.value)}
							/>
						</Group>
						<Group position='apart'>
							<Button variant='gradient' size='md' onClick={() => getWeatherData()}>
								Get Weather
							</Button>
						</Group>
					</Paper>
				</div>
			</main>
		</div>
	);
}
